server:
  port: 8081

spring:
  datasource:
    url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=BalanceDB;trustServerCertificate=true
    username: sa
    password: ${SA_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
