server:
  port: 8081

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=BalanceDB;encrypt=false
    username: sa
    password: ${SA_PASSWORD:MssqlK8s!}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
